// Central tool catalog: every registered function's routing metadata.
// Used by (1) Gemini function declarations, (2) toolRegistry registration,
// and (3) skill routing / validation. One source of truth.

import type { SkillDomain, RiskLevel } from './skills/types.js';
import { findSkillsByTool, getSkill } from './skills/index.js';

export interface ToolCatalogEntry {
  name: string;
  domain: SkillDomain;
  risk: RiskLevel;
  description: string;
  /** Skills that use this tool. */
  skillRoutes: string[];
  /** Requirements the tool needs to function. */
  requirements: string[];
  /** Other tools that conflict with this one. */
  conflictsWith: string[];
  /** Example queries that should trigger this tool. */
  positiveExamples: string[];
  /** Example queries that should NOT trigger this tool. */
  negativeExamples: string[];
  /** Whether this tool needs a Gemini confirmation before executing. */
  requiresConfirmation?: boolean;
}

const CATALOG: ToolCatalogEntry[] = [
  // ── Code & Computing ────────────────────────────────────────────────────
  {
    name: 'executeCodeSandbox',
    domain: 'code',
    risk: 'execute',
    description: 'Execute isolated code in a sandboxed environment',
    skillRoutes: ['code.run_snippet'],
    requirements: [],
    conflictsWith: ['runCodingAgent'],
    positiveExamples: ['run this JS snippet', 'execute a python function', 'show me a quick HTML page'],
    negativeExamples: ['explain this code', 'build a feature in my repo', 'run npm test'],
  },
  {
    name: 'runCliCommand',
    domain: 'code',
    risk: 'execute',
    description: 'Run a shell/CLI command',
    skillRoutes: ['code.run_command'],
    requirements: [],
    conflictsWith: ['runCodingAgent'],
    positiveExamples: ['run npm test', 'git status', 'ls -la', 'node -v'],
    negativeExamples: ['edit my code', 'build a feature', 'refactor this module'],
  },
  {
    name: 'openLocalTerminal',
    domain: 'code',
    risk: 'execute',
    description: 'Open a local terminal session',
    skillRoutes: ['system.terminal'],
    requirements: [],
    conflictsWith: [],
    positiveExamples: ['open a terminal', 'give me a shell'],
    negativeExamples: ['run a specific command'],
  },
  {
    name: 'deployAgentTask',
    domain: 'code',
    risk: 'write',
    description: 'Deploy a sub-agent to perform a task',
    skillRoutes: ['code.review_repository', 'code.modify_repository'],
    requirements: [],
    conflictsWith: ['executeCodeSandbox', 'runCliCommand'],
    positiveExamples: ['review this codebase', 'audit my project', 'find bugs'],
    negativeExamples: ['run a single command', 'execute a snippet'],
  },
  {
    name: 'runCodingAgent',
    domain: 'code',
    risk: 'write',
    description: 'Spawn OpenCode CLI for autonomous code editing',
    skillRoutes: ['code.modify_repository'],
    requirements: [],
    conflictsWith: ['executeCodeSandbox', 'runCliCommand'],
    positiveExamples: ['build a dashboard in this repo', 'implement login', 'refactor the auth module', 'fix the bug in payment'],
    negativeExamples: ['run npm test', 'explain this code', 'what does this function do'],
  },
  {
    name: 'getSystemInfo',
    domain: 'system',
    risk: 'read',
    description: 'Get system information (OS, CPU, memory, disk)',
    skillRoutes: ['system.info'],
    requirements: [],
    conflictsWith: [],
    positiveExamples: ['what are the system specs', 'how much disk space'],
    negativeExamples: ['run a command'],
  },
  {
    name: 'updateCanvasVisual',
    domain: 'presentation',
    risk: 'write',
    description: 'Update the canvas with diagrams, markdown, charts, or code snippets',
    skillRoutes: ['presentation.canvas'],
    requirements: [],
    conflictsWith: [],
    positiveExamples: ['show me a diagram', 'create a chart', 'display this as markdown'],
    negativeExamples: ['generate an image', 'create a document'],
  },
  {
    name: 'getWeather',
    domain: 'web',
    risk: 'read',
    description: 'Get current weather for a location',
    skillRoutes: ['web.weather'],
    requirements: [],
    conflictsWith: [],
    positiveExamples: ['what is the weather', 'is it raining in Manila'],
    negativeExamples: ['search for weather news'],
  },
  {
    name: 'webSearch',
    domain: 'web',
    risk: 'read',
    description: 'Search the web for information',
    skillRoutes: ['web.research'],
    requirements: [],
    conflictsWith: ['runBrowserAutomation'],
    positiveExamples: ['find documentation', 'search for news', 'look up prices'],
    negativeExamples: ['open a website and click something', 'fill out a form online'],
  },
  {
    name: 'runBrowserAutomation',
    domain: 'browser',
    risk: 'execute',
    description: 'Control a headless browser for page interaction',
    skillRoutes: ['web.browser_action'],
    requirements: [],
    conflictsWith: ['webSearch'],
    positiveExamples: ['open gemini docs and click API reference', 'navigate to github.com'],
    negativeExamples: ['find me some documentation', 'search for news'],
  },
  {
    name: 'runComputerControl',
    domain: 'computer',
    risk: 'execute',
    description: 'Control native desktop applications',
    skillRoutes: ['computer.open_app', 'computer.shell', 'computer.workflow'],
    requirements: [],
    conflictsWith: [],
    positiveExamples: ['open the calculator', 'use the spreadsheet app', 'click Save'],
    negativeExamples: ['search the web', 'run a CLI command'],
  },

  // ── Media / QwenCloud ───────────────────────────────────────────────────
  {
    name: 'qwenChat',
    domain: 'media',
    risk: 'generate',
    description: 'Text chat with QwenCloud LLM',
    skillRoutes: ['media.chat'],
    requirements: ['DASHSCOPE_API_KEY'],
    conflictsWith: [],
    positiveExamples: ['ask Qwen about something'],
    negativeExamples: ['generate an image', 'create a video'],
  },
  {
    name: 'qwenImageGenerate',
    domain: 'media',
    risk: 'generate',
    description: 'Generate an image from a text prompt via QwenCloud',
    skillRoutes: ['media.image.generate'],
    requirements: ['DASHSCOPE_API_KEY'],
    conflictsWith: ['qwenImageEdit'],
    positiveExamples: ['create an image of a robot', 'generate a picture of sunset', 'make me a logo'],
    negativeExamples: ['edit this image', 'remove the person from this photo', 'how does image gen work'],
  },
  {
    name: 'qwenImageEdit',
    domain: 'media',
    risk: 'generate',
    description: 'Edit an existing image via QwenCloud',
    skillRoutes: ['media.image.edit'],
    requirements: ['DASHSCOPE_API_KEY', 'activeImage'],
    conflictsWith: ['qwenImageGenerate'],
    positiveExamples: ['edit this image and remove the background', 'make the sky blue', 'add text to this image'],
    negativeExamples: ['generate a new image from scratch', 'create a picture of a robot'],
  },
  {
    name: 'qwenVideoGenerate',
    domain: 'media',
    risk: 'generate',
    description: 'Generate a video from a text prompt via QwenCloud (canonical route)',
    skillRoutes: ['media.video.generate'],
    requirements: ['DASHSCOPE_API_KEY'],
    conflictsWith: ['generateVideo'],
    positiveExamples: ['create a video of waves', 'generate a cinematic clip', 'make a short video'],
    negativeExamples: ['edit this video', 'generate an image', 'what is video generation'],
  },
  {
    name: 'generateVideo',
    domain: 'media',
    risk: 'generate',
    description: 'Generate video via DashScope (legacy/alternative — prefer qwenVideoGenerate)',
    skillRoutes: ['media.video.generate'],
    requirements: ['DASHSCOPE_API_KEY'],
    conflictsWith: ['qwenVideoGenerate'],
    positiveExamples: [],
    negativeExamples: ['use qwenVideoGenerate for all video generation'],
  },
  {
    name: 'qwenTts',
    domain: 'media',
    risk: 'generate',
    description: 'Text-to-speech via QwenCloud',
    skillRoutes: ['media.audio.tts'],
    requirements: ['DASHSCOPE_API_KEY'],
    conflictsWith: [],
    positiveExamples: ['read this text aloud', 'generate speech for this paragraph', 'narrate this'],
    negativeExamples: ['generate an image', 'send a message'],
  },

  // ── Google Workspace ────────────────────────────────────────────────────
  {
    name: 'connectGoogleAccount',
    domain: 'google',
    risk: 'read',
    description: 'Check Google OAuth connection status',
    skillRoutes: ['google.connect'],
    requirements: [],
    conflictsWith: [],
    positiveExamples: [],
    negativeExamples: [],
  },
  {
    name: 'listGmailMessages',
    domain: 'google',
    risk: 'read',
    description: 'List or search Gmail messages',
    skillRoutes: ['google.gmail.list', 'google.gmail.search'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['show my latest emails', 'find emails from Michael', 'search gmail for invoice'],
    negativeExamples: ['send an email', 'delete emails'],
  },
  {
    name: 'getGmailMessage',
    domain: 'google',
    risk: 'read',
    description: 'Read a specific Gmail message',
    skillRoutes: ['google.gmail.read'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['read that email', 'open the latest message', 'what did Michael send'],
    negativeExamples: ['send a reply', 'delete the email'],
  },
  {
    name: 'sendGmailMessage',
    domain: 'google',
    risk: 'write',
    description: 'Send a Gmail message',
    skillRoutes: ['google.gmail.send'],
    requirements: ['google_auth'],
    conflictsWith: ['send_whatsapp_text'],
    positiveExamples: ['send an email to Michael', 'email the team about the meeting'],
    negativeExamples: ['show my emails', 'read that email', 'send a WhatsApp message'],
  },
  {
    name: 'createGmailDraft',
    domain: 'google',
    risk: 'write',
    description: 'Create a Gmail draft',
    skillRoutes: ['google.gmail.draft'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['draft an email to Michael', 'save this as a draft'],
    negativeExamples: ['send the email now', 'show my inbox'],
  },
  {
    name: 'modifyGmailMessage',
    domain: 'google',
    risk: 'write',
    description: 'Modify Gmail labels (mark read, archive, etc.)',
    skillRoutes: ['google.gmail.modify'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['mark as read', 'archive this email'],
    negativeExamples: ['delete the email', 'send a reply'],
  },
  {
    name: 'trashGmailMessage',
    domain: 'google',
    risk: 'destructive',
    description: 'Move a Gmail message to trash',
    skillRoutes: ['google.gmail.trash'],
    requirements: ['google_auth'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['trash this email', 'delete that email'],
    negativeExamples: ['archive the email', 'mark as unread'],
  },
  {
    name: 'deleteGmailMessage',
    domain: 'google',
    risk: 'destructive',
    description: 'Permanently delete a Gmail message',
    skillRoutes: ['google.gmail.delete'],
    requirements: ['google_auth'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['permanently delete that email'],
    negativeExamples: ['trash it', 'archive it'],
  },
  {
    name: 'listCalendarEvents',
    domain: 'google',
    risk: 'read',
    description: 'List Google Calendar events',
    skillRoutes: ['google.calendar.list'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['show my calendar', 'what meetings do I have today', 'list upcoming events'],
    negativeExamples: ['create a meeting', 'delete an event'],
  },
  {
    name: 'createCalendarEvent',
    domain: 'google',
    risk: 'write',
    description: 'Create a Google Calendar event',
    skillRoutes: ['google.calendar.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['schedule a meeting', 'create an event for tomorrow', 'block time for lunch'],
    negativeExamples: ['show my calendar', 'what meetings do I have'],
  },
  {
    name: 'updateCalendarEvent',
    domain: 'google',
    risk: 'write',
    description: 'Update an existing Google Calendar event',
    skillRoutes: ['google.calendar.update'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['move the meeting to 3pm', 'update the event title'],
    negativeExamples: ['create a new event', 'show my calendar'],
  },
  {
    name: 'deleteCalendarEvent',
    domain: 'google',
    risk: 'destructive',
    description: 'Delete a Google Calendar event',
    skillRoutes: ['google.calendar.delete'],
    requirements: ['google_auth'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['cancel that meeting', 'delete the event'],
    negativeExamples: ['show my calendar', 'reschedule the meeting'],
  },
  {
    name: 'createGoogleMeet',
    domain: 'google',
    risk: 'write',
    description: 'Create a Google Meet link',
    skillRoutes: ['google.calendar.create_meet'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['create a meeting link', 'start a Google Meet'],
    negativeExamples: ['schedule a meeting with an invite'],
  },
  {
    name: 'listDriveFiles',
    domain: 'google',
    risk: 'read',
    description: 'List Google Drive files',
    skillRoutes: ['google.drive.list'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['show my Drive files', 'what is in my Google Drive'],
    negativeExamples: ['create a file', 'delete a file'],
  },
  {
    name: 'searchDriveFiles',
    domain: 'google',
    risk: 'read',
    description: 'Search Google Drive files by name',
    skillRoutes: ['google.drive.search'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['find the budget spreadsheet', 'search Drive for invoice'],
    negativeExamples: ['create a new document', 'delete a file'],
  },
  {
    name: 'getDriveFile',
    domain: 'google',
    risk: 'read',
    description: 'Read Google Drive file content and metadata',
    skillRoutes: ['google.drive.read'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['open that document', 'read the file content'],
    negativeExamples: ['edit the file', 'create a new file'],
  },
  {
    name: 'createDriveFile',
    domain: 'google',
    risk: 'write',
    description: 'Create a new Google Drive file',
    skillRoutes: ['google.drive.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['create a new document in Drive', 'save this to Drive'],
    negativeExamples: ['read a file', 'search Drive'],
  },
  {
    name: 'updateDriveFileContent',
    domain: 'google',
    risk: 'write',
    description: 'Update Google Drive file content',
    skillRoutes: ['google.drive.update'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['update the document', 'replace the file content'],
    negativeExamples: ['read the file', 'create a new file'],
  },
  {
    name: 'deleteDriveFile',
    domain: 'google',
    risk: 'destructive',
    description: 'Delete a Google Drive file (moves to trash)',
    skillRoutes: ['google.drive.delete'],
    requirements: ['google_auth'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['delete that file', 'remove from Drive'],
    negativeExamples: ['archive the file', 'read the file'],
  },
  {
    name: 'createGoogleDoc',
    domain: 'google',
    risk: 'write',
    description: 'Create a new Google Document',
    skillRoutes: ['google.docs.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['create a new document', 'write this to a Google Doc'],
    negativeExamples: ['edit an existing doc', 'read a document'],
  },
  {
    name: 'createGoogleSheet',
    domain: 'google',
    risk: 'write',
    description: 'Create a new Google Spreadsheet',
    skillRoutes: ['google.sheets.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['create a spreadsheet', 'make a new Google Sheet'],
    negativeExamples: ['edit an existing sheet', 'read a spreadsheet'],
  },
  {
    name: 'createGoogleSlide',
    domain: 'google',
    risk: 'write',
    description: 'Create a new Google Slides presentation',
    skillRoutes: ['google.slides.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['create a presentation', 'make slides for my pitch'],
    negativeExamples: ['edit existing slides', 'show me a presentation'],
  },
  {
    name: 'listGoogleForms',
    domain: 'google',
    risk: 'read',
    description: 'List Google Forms',
    skillRoutes: ['google.forms.list'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['show my forms', 'list my Google Forms'],
    negativeExamples: ['create a form'],
  },
  {
    name: 'createGoogleForm',
    domain: 'google',
    risk: 'write',
    description: 'Create a new Google Form',
    skillRoutes: ['google.forms.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['create a feedback form', 'make a survey'],
    negativeExamples: ['show my forms', 'edit a form'],
  },
  {
    name: 'listGoogleTasks',
    domain: 'google',
    risk: 'read',
    description: 'List Google Tasks',
    skillRoutes: ['google.tasks.list'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['show my tasks', 'what tasks do I have', 'list my to-dos'],
    negativeExamples: ['create a task', 'delete a task'],
  },
  {
    name: 'createGoogleTask',
    domain: 'google',
    risk: 'write',
    description: 'Create a Google Task',
    skillRoutes: ['google.tasks.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['add a task', 'remind me to call Michael', 'create a to-do'],
    negativeExamples: ['show my tasks', 'complete a task'],
  },
  {
    name: 'updateGoogleTask',
    domain: 'google',
    risk: 'write',
    description: 'Update a Google Task',
    skillRoutes: ['google.tasks.update'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['mark that task complete', 'update the task title'],
    negativeExamples: ['create a new task', 'list my tasks'],
  },
  {
    name: 'deleteGoogleTask',
    domain: 'google',
    risk: 'destructive',
    description: 'Delete a Google Task',
    skillRoutes: ['google.tasks.delete'],
    requirements: ['google_auth'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['delete that task', 'remove the to-do'],
    negativeExamples: ['complete the task', 'list my tasks'],
  },
  {
    name: 'listGoogleContacts',
    domain: 'google',
    risk: 'read',
    description: 'List or search Google Contacts',
    skillRoutes: ['google.contacts.list'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['find Michael in my contacts', 'show my contacts'],
    negativeExamples: ['add a contact', 'send a message'],
  },
  {
    name: 'createGoogleContact',
    domain: 'google',
    risk: 'write',
    description: 'Create a Google Contact',
    skillRoutes: ['google.contacts.create'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['add a new contact', 'save this person to my contacts'],
    negativeExamples: ['find a contact', 'send a message'],
  },
  {
    name: 'updateGoogleContact',
    domain: 'google',
    risk: 'write',
    description: 'Update a Google Contact',
    skillRoutes: ['google.contacts.update'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['update Michael\'s phone number', 'change the email'],
    negativeExamples: ['find a contact', 'delete a contact'],
  },
  {
    name: 'deleteGoogleContact',
    domain: 'google',
    risk: 'destructive',
    description: 'Delete a Google Contact',
    skillRoutes: ['google.contacts.delete'],
    requirements: ['google_auth'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['delete this contact', 'remove Michael from my contacts'],
    negativeExamples: ['find a contact', 'update a contact'],
  },
  {
    name: 'searchYoutube',
    domain: 'google',
    risk: 'read',
    description: 'Search YouTube videos',
    skillRoutes: ['google.youtube.search'],
    requirements: ['google_auth'],
    conflictsWith: [],
    positiveExamples: ['find a tutorial on React', 'search YouTube for cooking videos'],
    negativeExamples: ['play a video', 'download a video'],
  },

  // ── WhatsApp ────────────────────────────────────────────────────────────
  {
    name: 'resolve_whatsapp_contact',
    domain: 'whatsapp',
    risk: 'read',
    description: 'Resolve a contact name/number to a WhatsApp JID',
    skillRoutes: ['whatsapp.resolve_contact'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: [],
    negativeExamples: [],
  },
  {
    name: 'request_whatsapp_send',
    domain: 'whatsapp',
    risk: 'read',
    description: 'Request human approval before sending a WhatsApp message',
    skillRoutes: ['whatsapp.send_message'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: [],
    negativeExamples: [],
  },
  {
    name: 'send_whatsapp_text',
    domain: 'whatsapp',
    risk: 'write',
    description: 'Send a text message via WhatsApp',
    skillRoutes: ['whatsapp.send_message'],
    requirements: ['whatsapp_connected', 'resolved_contact'],
    conflictsWith: ['sendGmailMessage'],
    positiveExamples: ['send Michael a message', 'text the group', 'reply to that chat'],
    negativeExamples: ['read my chats', 'show contacts', 'send an email'],
  },
  {
    name: 'send_whatsapp_contact_card',
    domain: 'whatsapp',
    risk: 'write',
    description: 'Send a contact card via WhatsApp',
    skillRoutes: ['whatsapp.send_contact_card'],
    requirements: ['whatsapp_connected', 'resolved_contact'],
    conflictsWith: [],
    positiveExamples: ['send Michael\'s contact to Sarah', 'share a contact card'],
    negativeExamples: ['send a text message', 'send a document'],
  },
  {
    name: 'send_whatsapp_message',
    domain: 'whatsapp',
    risk: 'write',
    description: 'Send a rich message (image/video/audio) via WhatsApp',
    skillRoutes: ['whatsapp.send_message'],
    requirements: ['whatsapp_connected', 'resolved_contact'],
    conflictsWith: [],
    positiveExamples: ['send this image to Michael', 'forward this video'],
    negativeExamples: ['send a text message', 'read chats'],
  },
  {
    name: 'send_whatsapp_group_message',
    domain: 'whatsapp',
    risk: 'write',
    description: 'Send a message to a WhatsApp group',
    skillRoutes: ['whatsapp.send_group_message'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['send to the family group', 'message the team group'],
    negativeExamples: ['send a private message', 'list groups'],
  },
  {
    name: 'send_whatsapp_document',
    domain: 'whatsapp',
    risk: 'write',
    description: 'Send a document via WhatsApp',
    skillRoutes: ['whatsapp.send_document'],
    requirements: ['whatsapp_connected', 'resolved_contact'],
    conflictsWith: [],
    positiveExamples: ['send this file to Michael', 'share the document'],
    negativeExamples: ['send a text message', 'send an image'],
  },
  {
    name: 'read_whatsapp_chats',
    domain: 'whatsapp',
    risk: 'read',
    description: 'Read WhatsApp chat list',
    skillRoutes: ['whatsapp.list_chats'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['show my chats', 'list WhatsApp conversations'],
    negativeExamples: ['send a message', 'read message history'],
  },
  {
    name: 'get_whatsapp_contacts',
    domain: 'whatsapp',
    risk: 'read',
    description: 'List or search WhatsApp contacts',
    skillRoutes: ['whatsapp.list_contacts'],
    requirements: ['whatsapp_connected'],
    conflictsWith: ['listGoogleContacts'],
    positiveExamples: ['show my WhatsApp contacts', 'find Michael on WhatsApp'],
    negativeExamples: ['send a message', 'add a contact'],
  },
  {
    name: 'get_whatsapp_groups',
    domain: 'whatsapp',
    risk: 'read',
    description: 'List WhatsApp groups',
    skillRoutes: ['whatsapp.list_groups'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['show my groups', 'list WhatsApp groups'],
    negativeExamples: ['send a group message', 'create a group'],
  },
  {
    name: 'get_whatsapp_message_history',
    domain: 'whatsapp',
    risk: 'read',
    description: 'Read message history for a WhatsApp chat',
    skillRoutes: ['whatsapp.read_history'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['read my chat with Michael', 'show conversation history', 'what did Michael say'],
    negativeExamples: ['send a message', 'list chats'],
  },
  {
    name: 'get_whatsapp_calls',
    domain: 'whatsapp',
    risk: 'read',
    description: 'List WhatsApp call history',
    skillRoutes: ['whatsapp.list_calls'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['show my WhatsApp calls', 'who called me'],
    negativeExamples: ['make a call', 'send a message'],
  },
  {
    name: 'block_whatsapp_contact',
    domain: 'whatsapp',
    risk: 'destructive',
    description: 'Block a WhatsApp contact',
    skillRoutes: ['whatsapp.block'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['block Michael on WhatsApp', 'block this number'],
    negativeExamples: ['unblock a contact', 'send a message'],
  },
  {
    name: 'unblock_whatsapp_contact',
    domain: 'whatsapp',
    risk: 'write',
    description: 'Unblock a WhatsApp contact',
    skillRoutes: ['whatsapp.unblock'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['unblock Michael', 'remove block'],
    negativeExamples: ['block a contact'],
  },
  {
    name: 'read_whatsapp_attachment',
    domain: 'whatsapp',
    risk: 'read',
    description: 'Read/download a WhatsApp attachment',
    skillRoutes: ['whatsapp.read_attachment'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['open that attachment', 'download the image'],
    negativeExamples: ['send an attachment', 'read message history'],
  },
  {
    name: 'transcribe_whatsapp_audio',
    domain: 'whatsapp',
    risk: 'read',
    description: 'Transcribe a WhatsApp audio message',
    skillRoutes: ['whatsapp.transcribe_audio'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['transcribe that voice message', 'what did they say in the audio'],
    negativeExamples: ['send an audio message', 'play the audio'],
  },
  {
    name: 'sync_whatsapp_history',
    domain: 'whatsapp',
    risk: 'read',
    description: 'Sync WhatsApp message history from the server',
    skillRoutes: ['whatsapp.sync'],
    requirements: ['whatsapp_connected'],
    conflictsWith: [],
    positiveExamples: ['sync my WhatsApp messages', 'refresh chat history'],
    negativeExamples: ['read chats', 'send a message'],
  },
  {
    name: 'whatsapp_call',
    domain: 'whatsapp',
    risk: 'execute',
    description: 'Initiate a WhatsApp voice/video call',
    skillRoutes: ['whatsapp.call'],
    requirements: ['whatsapp_connected', 'resolved_contact'],
    conflictsWith: [],
    requiresConfirmation: true,
    positiveExamples: ['call Michael on WhatsApp', 'start a voice call'],
    negativeExamples: ['send a message', 'list contacts'],
  },

  // ── Memory ──────────────────────────────────────────────────────────────
  {
    name: 'remember_memory',
    domain: 'memory',
    risk: 'write',
    description: 'Store a memory for long-term recall',
    skillRoutes: ['memory.remember'],
    requirements: ['memory_service'],
    conflictsWith: [],
    positiveExamples: ['remember that my birthday is March 15', 'save this fact'],
    negativeExamples: ['recall a memory', 'what did you remember'],
  },
  {
    name: 'recall_memory',
    domain: 'memory',
    risk: 'read',
    description: 'Search long-term memory for relevant context',
    skillRoutes: ['memory.recall'],
    requirements: ['memory_service'],
    conflictsWith: [],
    positiveExamples: ['what do you know about my family', 'recall our previous conversation'],
    negativeExamples: ['remember this', 'forget that'],
  },
  {
    name: 'get_core_memory',
    domain: 'memory',
    risk: 'read',
    description: 'Read the core persona profile from memory',
    skillRoutes: ['memory.core_profile'],
    requirements: ['memory_service'],
    conflictsWith: [],
    positiveExamples: ['show core profile', 'what is your persona'],
    negativeExamples: ['remember something', 'recall a memory'],
  },
];

// ── Lookup helpers ─────────────────────────────────────────────────────────

const byName = new Map<string, ToolCatalogEntry>();
for (const entry of CATALOG) byName.set(entry.name, entry);

/** Get a tool's catalog entry (returns undefined for unregistered tools). */
export function getToolCatalogEntry(name: string): ToolCatalogEntry | undefined {
  return byName.get(name);
}

/** Get all catalog entries. */
export function getAllToolCatalogEntries(): readonly ToolCatalogEntry[] {
  return CATALOG;
}

/** Find all tools that belong to a skill route. */
export function findToolsForSkill(skillId: string): ToolCatalogEntry[] {
  return CATALOG.filter((e) => e.skillRoutes.includes(skillId));
}

/** Find all tools in a domain. */
export function findToolsByDomain(domain: SkillDomain): ToolCatalogEntry[] {
  return CATALOG.filter((e) => e.domain === domain);
}

/** Get just the tool names (for coverage checks). */
export function getAllToolNames(): string[] {
  return CATALOG.map((e) => e.name);
}

/**
 * Verify that every registered tool has at least one skill route.
 * Returns an array of unassigned tool names (empty = all covered).
 *
 * A tool is assigned when either:
 *   - a skill route's steps use it directly (findSkillsByTool), or
 *   - it declares skillRoutes that resolve to existing skills
 *     (reroute/alias coverage, e.g. generateVideo → media.video.generate).
 * Declared routes pointing at unknown skill IDs are treated as unassigned.
 */
export function findUnassignedTools(): string[] {
  return CATALOG.filter((e) => {
    if (e.skillRoutes.length === 0) return true;
    const hasDirectStep = findSkillsByTool(e.name).length > 0;
    const hasResolvableRoute = e.skillRoutes.some((id) => getSkill(id) !== undefined);
    return !hasDirectStep && !hasResolvableRoute;
  }).map((e) => e.name);
}

/**
 * Return tools whose declared skillRoutes reference skill IDs that do not
 * exist (e.g. typos, wildcards like 'google.*'). Empty = all declarations valid.
 */
export function findInvalidSkillRouteDeclarations(): string[] {
  return CATALOG.filter((e) =>
    e.skillRoutes.some((id) => getSkill(id) === undefined),
  ).map((e) => e.name);
}
