import type { SkillRoute } from './types.js';

export const computerSkills: SkillRoute[] = [
  {
    id: 'computer.open_app',
    domain: 'computer',
    intents: ['execute', 'control'],
    description: 'Open a native desktop application',
    triggers: ['open the', 'launch', 'open app', 'start the', 'open application', 'open calculator', 'open browser app', 'run the app'],
    negativeTriggers: ['search', 'look up', 'find', 'what is', 'browse the web'],
    risk: 'execute',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'App name is specified.',
        onFailure: 'Ask which application to open.',
      },
      {
        id: 'open',
        action: 'tool',
        tool: 'runComputerControl',
        argsBuilder: (ctx) => ({
          action: 'openApp',
          app: ctx.app,
        }),
        required: true,
        onSuccess: 'Application opened.',
        onFailure: 'Report the error or check the computer service.',
      },
      { id: 'respond', action: 'respond' },
    ],
    successCriteria: [
      { name: 'app_opened', description: 'Computer service confirmed the app launched' },
    ],
    outputMode: 'action',
  },
  {
    id: 'computer.shell',
    domain: 'computer',
    intents: ['execute', 'control'],
    description: 'Run a shell command on the desktop computer',
    triggers: ['run on the computer', 'shell command', 'execute on desktop', 'computer terminal', 'run this command on the pc'],
    negativeTriggers: ['open app', 'click', 'type', 'move the mouse'],
    risk: 'execute',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Command is specified.',
        onFailure: 'Ask which command to run.',
      },
      {
        id: 'run',
        action: 'tool',
        tool: 'runComputerControl',
        argsBuilder: (ctx) => ({
          action: 'shell',
          command: ctx.command,
        }),
        required: true,
        onSuccess: 'Command output returned.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'computer.mouse',
    domain: 'computer',
    intents: ['control', 'execute'],
    description: 'Move the mouse or click on the desktop',
    triggers: ['move the mouse', 'click', 'double click', 'click on', 'right click', 'drag'],
    negativeTriggers: ['type', 'keyboard', 'open app', 'run command'],
    risk: 'execute',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Click/move target is specified.',
        onFailure: 'Ask what to click or where to move.',
      },
      {
        id: 'click',
        action: 'tool',
        tool: 'runComputerControl',
        argsBuilder: (ctx) => ({
          action: ctx.clickAction || 'click',
          x: ctx.x,
          y: ctx.y,
        }),
        required: true,
        onSuccess: 'Mouse action completed.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'computer.keyboard',
    domain: 'computer',
    intents: ['control', 'execute'],
    description: 'Send keyboard shortcuts or keys on the desktop',
    triggers: ['press', 'shortcut', 'keyboard shortcut', 'ctrl', 'alt', 'esc', 'enter key'],
    negativeTriggers: ['type text', 'write', 'open app', 'click'],
    risk: 'execute',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Keys are specified.',
        onFailure: 'Ask which keys to press.',
      },
      {
        id: 'press',
        action: 'tool',
        tool: 'runComputerControl',
        argsBuilder: (ctx) => ({
          action: 'key',
          keys: ctx.keys,
        }),
        required: true,
        onSuccess: 'Keys pressed.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'computer.type',
    domain: 'computer',
    intents: ['control', 'create', 'execute'],
    description: 'Type text into the focused desktop application',
    triggers: ['type', 'type text', 'enter text', 'write in the app', 'fill in', 'input text'],
    negativeTriggers: ['press shortcut', 'open app', 'click'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Text is specified.',
        onFailure: 'Ask what text to type.',
      },
      {
        id: 'type',
        action: 'tool',
        tool: 'runComputerControl',
        argsBuilder: (ctx) => ({
          action: 'type',
          text: ctx.text,
        }),
        required: true,
        onSuccess: 'Text typed.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'computer.workflow',
    domain: 'computer',
    intents: ['execute', 'control', 'create'],
    description: 'Multi-step computer task: plan a sequence, act, observe, iterate',
    triggers: ['do this on the computer', 'automate', 'workflow', 'set up', 'perform the task', 'complete this task'],
    negativeTriggers: ['search the web', 'send a message', 'open a browser'],
    risk: 'execute',
    steps: [
      {
        id: 'plan',
        action: 'analyze',
        required: true,
        onSuccess: 'Goal understood.',
        onFailure: 'Ask the user to clarify the goal.',
      },
      {
        id: 'act',
        action: 'tool',
        tool: 'runComputerControl',
        argsBuilder: (ctx) => ({
          action: 'workflow',
          goal: ctx.goal,
        }),
        required: true,
        onSuccess: 'Workflow completed.',
        onFailure: 'Report the step that failed.',
      },
      { id: 'respond', action: 'respond' },
    ],
    successCriteria: [
      { name: 'goal_reached', description: 'Final state matches the requested goal' },
    ],
    outputMode: 'action',
  },
];

export default computerSkills;