import type { SkillRoute } from './types.js';

export const googleSkills: SkillRoute[] = [
  // ── Connection ────────────────────────────────────────────────────────────
  {
    id: 'google.connect',
    domain: 'google',
    intents: ['read', 'question'],
    description: 'Check or establish the Google account connection',
    triggers: ['connect google', 'google account', 'connect my google', 'authorize', 'sign in with google', 'is google connected', 'reconnect google'],
    negativeTriggers: ['send an email', 'create a calendar event', 'search youtube'],
    risk: 'read',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Connection request is clear.',
        onFailure: 'Ask the user what they need Google for.',
      },
      {
        id: 'connect',
        action: 'tool',
        tool: 'connectGoogleAccount',
        required: true,
        onSuccess: 'Google connection status returned.',
        onFailure: 'Report the auth error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  // ── Gmail ─────────────────────────────────────────────────────────────────
  {
    id: 'google.gmail.list',
    domain: 'google',
    intents: ['read', 'search'],
    description: 'List or search Gmail messages',
    triggers: ['emails', 'gmail', 'inbox', 'messages from', 'email from', 'find email'],
    negativeTriggers: ['send an email', 'compose', 'reply to', 'forward', 'search'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'listGmailMessages',
        argsBuilder: (ctx) => ({
          query: ctx.query,
          maxResults: ctx.maxResults,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.gmail.search',
    domain: 'google',
    intents: ['search', 'read'],
    description: 'Search Gmail for messages matching a query',
    triggers: ['search my emails', 'find email', 'search gmail', 'look for an email', 'email about'],
    negativeTriggers: ['send an email', 'reply to', 'delete'],
    risk: 'read',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Search query is valid.',
        onFailure: 'Ask what to search for.',
      },
      {
        id: 'search',
        action: 'tool',
        tool: 'listGmailMessages',
        argsBuilder: (ctx) => ({
          query: ctx.query,
          maxResults: ctx.maxResults,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.gmail.read',
    domain: 'google',
    intents: ['read'],
    description: 'Read a specific Gmail message',
    triggers: ['read email', 'open email', 'what did', 'show me the email', 'read that message'],
    negativeTriggers: ['send', 'reply', 'forward', 'delete'],
    risk: 'read',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'message is ambiguous',
        onSuccess: 'Message resolved.',
        onFailure: 'Ask which email to read.',
      },
      {
        id: 'read',
        action: 'tool',
        tool: 'getGmailMessage',
        argsBuilder: (ctx) => ({ messageId: ctx.messageId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.gmail.send',
    domain: 'google',
    intents: ['send', 'create'],
    description: 'Send a Gmail message',
    triggers: ['send email', 'email to', 'compose email', 'write to', 'mail to'],
    negativeTriggers: ['show emails', 'read email', 'list inbox'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Email details are complete.',
        onFailure: 'Ask for recipient, subject, and body.',
      },
      {
        id: 'send',
        action: 'tool',
        tool: 'sendGmailMessage',
        argsBuilder: (ctx) => ({
          to: ctx.to,
          subject: ctx.subject,
          body: ctx.body,
          cc: ctx.cc,
          bcc: ctx.bcc,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    successCriteria: [
      { name: 'email_sent', description: 'Gmail message was delivered' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.gmail.draft',
    domain: 'google',
    intents: ['create'],
    description: 'Create a Gmail draft',
    triggers: ['draft email', 'save as draft', 'draft to'],
    negativeTriggers: ['send email', 'show inbox'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'draft',
        action: 'tool',
        tool: 'createGmailDraft',
        argsBuilder: (ctx) => ({
          to: ctx.to,
          subject: ctx.subject,
          body: ctx.body,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.gmail.modify',
    domain: 'google',
    intents: ['edit'],
    description: 'Modify Gmail labels (mark read, archive)',
    triggers: ['mark as read', 'archive', 'mark unread', 'label'],
    negativeTriggers: ['delete', 'send'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'message is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which email.',
      },
      {
        id: 'modify',
        action: 'tool',
        tool: 'modifyGmailMessage',
        argsBuilder: (ctx) => ({
          messageId: ctx.messageId,
          addLabels: ctx.addLabels,
          removeLabels: ctx.removeLabels,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.gmail.trash',
    domain: 'google',
    intents: ['delete'],
    description: 'Move a Gmail message to trash',
    triggers: ['trash email', 'delete email', 'bin this'],
    negativeTriggers: ['archive', 'mark as read', 'meeting', 'event', 'calendar', 'permanently', 'forever'],
    risk: 'destructive',
    destructive: true,
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'message is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which email.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'trash',
        action: 'tool',
        tool: 'trashGmailMessage',
        argsBuilder: (ctx) => ({ messageId: ctx.messageId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.gmail.delete',
    domain: 'google',
    intents: ['delete'],
    description: 'Permanently delete a Gmail message',
    triggers: ['permanently delete', 'empty trash', 'delete forever', 'permanently', 'forever'],
    negativeTriggers: ['trash', 'archive', 'meeting', 'event', 'calendar'],
    risk: 'destructive',
    destructive: true,
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'message is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which email.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'delete',
        action: 'tool',
        tool: 'deleteGmailMessage',
        argsBuilder: (ctx) => ({ messageId: ctx.messageId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },

  // ── Calendar ──────────────────────────────────────────────────────────────
  {
    id: 'google.calendar.list',
    domain: 'google',
    intents: ['read'],
    description: 'List Google Calendar events',
    triggers: ['calendar', 'meetings', 'events today', 'schedule', 'what do i have', 'upcoming events', 'meeting'],
    negativeTriggers: ['create event', 'schedule meeting', 'cancel meeting', 'delete', 'remove', 'update', 'move', 'reschedule'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'listCalendarEvents',
        argsBuilder: (ctx) => ({
          timeMin: ctx.timeMin,
          timeMax: ctx.timeMax,
          maxResults: ctx.maxResults,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.calendar.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a Google Calendar event',
    triggers: ['schedule', 'create event', 'add to calendar', 'block time', 'set up meeting', 'book a meeting', 'create a meeting', 'meeting', 'appointment'],
    negativeTriggers: ['show calendar', 'list events', 'what meetings', 'delete', 'cancel'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Event details complete.',
        onFailure: 'Ask for event title, time, and duration.',
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createCalendarEvent',
        argsBuilder: (ctx) => ({
          summary: ctx.summary,
          start: ctx.start,
          end: ctx.end,
          description: ctx.description,
          attendees: ctx.attendees,
          location: ctx.location,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.calendar.update',
    domain: 'google',
    intents: ['edit'],
    description: 'Update an existing Google Calendar event',
    triggers: ['update event', 'move meeting', 'reschedule', 'change the meeting', 'update the event', 'move the meeting', 'update', 'move'],
    negativeTriggers: ['create event', 'show calendar'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'event is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which event to update.',
      },
      {
        id: 'update',
        action: 'tool',
        tool: 'updateCalendarEvent',
        argsBuilder: (ctx) => ({
          eventId: ctx.eventId,
          summary: ctx.summary,
          start: ctx.start,
          end: ctx.end,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.calendar.delete',
    domain: 'google',
    intents: ['delete'],
    description: 'Delete a Google Calendar event',
    triggers: ['cancel meeting', 'delete event', 'remove event', 'cancel that meeting', 'delete the meeting', 'delete meeting', 'meeting', 'event'],
    negativeTriggers: ['reschedule', 'update event', 'show', 'email'],
    risk: 'destructive',
    destructive: true,
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'event is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which event.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'delete',
        action: 'tool',
        tool: 'deleteCalendarEvent',
        argsBuilder: (ctx) => ({ eventId: ctx.eventId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.calendar.create_meet',
    domain: 'google',
    intents: ['create'],
    description: 'Create a Google Meet link',
    triggers: ['create meet', 'google meet', 'meeting link', 'start a meet', 'video call link'],
    negativeTriggers: ['schedule meeting with invite', 'create calendar event'],
    risk: 'write',
    steps: [
      {
        id: 'create',
        action: 'tool',
        tool: 'createGoogleMeet',
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },

  // ── Drive ─────────────────────────────────────────────────────────────────
  {
    id: 'google.drive.list',
    domain: 'google',
    intents: ['read'],
    description: 'List Google Drive files',
    triggers: ['drive files', 'google drive', 'my files', 'files in drive'],
    negativeTriggers: ['create file', 'delete file', 'search drive'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'listDriveFiles',
        argsBuilder: (ctx) => ({
          query: ctx.query,
          maxResults: ctx.maxResults,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.drive.search',
    domain: 'google',
    intents: ['search'],
    description: 'Search Google Drive files by name',
    triggers: ['find file', 'search drive', 'look for', 'where is the', 'find the document'],
    negativeTriggers: ['create file', 'list all files'],
    risk: 'read',
    steps: [
      {
        id: 'search',
        action: 'tool',
        tool: 'searchDriveFiles',
        argsBuilder: (ctx) => ({ query: ctx.query }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.drive.read',
    domain: 'google',
    intents: ['read'],
    description: 'Read Google Drive file content and metadata',
    triggers: ['open file', 'read document', 'show me the file', 'view the document'],
    negativeTriggers: ['create file', 'edit file', 'delete file'],
    risk: 'read',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'file is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which file to read.',
      },
      {
        id: 'read',
        action: 'tool',
        tool: 'getDriveFile',
        argsBuilder: (ctx) => ({ fileId: ctx.fileId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.drive.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a new Google Drive file',
    triggers: ['create file', 'new document', 'new spreadsheet', 'save to drive'],
    negativeTriggers: ['read file', 'search drive'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createDriveFile',
        argsBuilder: (ctx) => ({
          name: ctx.name,
          mimeType: ctx.mimeType,
          content: ctx.content,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.drive.update',
    domain: 'google',
    intents: ['edit'],
    description: 'Update Google Drive file content',
    triggers: ['update file', 'edit the document', 'replace content', 'overwrite the file'],
    negativeTriggers: ['read file', 'create file'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'file is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which file.',
      },
      {
        id: 'update',
        action: 'tool',
        tool: 'updateDriveFileContent',
        argsBuilder: (ctx) => ({
          fileId: ctx.fileId,
          content: ctx.content,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.drive.delete',
    domain: 'google',
    intents: ['delete'],
    description: 'Delete a Google Drive file',
    triggers: ['delete file', 'remove from drive', 'trash file'],
    negativeTriggers: ['read file', 'update file'],
    risk: 'destructive',
    destructive: true,
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'file is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which file.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'delete',
        action: 'tool',
        tool: 'deleteDriveFile',
        argsBuilder: (ctx) => ({ fileId: ctx.fileId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },

  // ── Docs / Sheets / Slides / Forms / Tasks / Contacts / YouTube ───────────
  {
    id: 'google.docs.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a new Google Document',
    triggers: ['new document', 'create a doc', 'write to google doc', 'google doc'],
    negativeTriggers: ['edit doc', 'read doc'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createGoogleDoc',
        argsBuilder: (ctx) => ({
          title: ctx.title,
          content: ctx.content,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.sheets.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a new Google Spreadsheet',
    triggers: ['new spreadsheet', 'create a sheet', 'google sheet', 'new excel'],
    negativeTriggers: ['edit sheet', 'read sheet'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createGoogleSheet',
        argsBuilder: (ctx) => ({
          title: ctx.title,
          content: ctx.content,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.slides.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a new Google Slides presentation',
    triggers: ['new presentation', 'create slides', 'google slides', 'make a pitch deck'],
    negativeTriggers: ['edit slides', 'read slides'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createGoogleSlide',
        argsBuilder: (ctx) => ({
          title: ctx.title,
          content: ctx.content,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.forms.list',
    domain: 'google',
    intents: ['read'],
    description: 'List Google Forms',
    triggers: ['my forms', 'list forms', 'google forms'],
    negativeTriggers: ['create form'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'listGoogleForms',
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.forms.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a new Google Form',
    triggers: ['create form', 'new form', 'survey', 'feedback form', 'google form'],
    negativeTriggers: ['list forms', 'edit form'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createGoogleForm',
        argsBuilder: (ctx) => ({
          title: ctx.title,
          questions: ctx.questions,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.tasks.list',
    domain: 'google',
    intents: ['read'],
    description: 'List Google Tasks',
    triggers: ['my tasks', 'to-do list', 'what tasks', 'task list', 'google tasks'],
    negativeTriggers: ['create task', 'complete task', 'delete task'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'listGoogleTasks',
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.tasks.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a Google Task',
    triggers: ['add a task', 'create task', 'new to-do', 'remind me to', 'task for'],
    negativeTriggers: ['list tasks', 'complete task', 'delete task'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createGoogleTask',
        argsBuilder: (ctx) => ({
          title: ctx.title,
          notes: ctx.notes,
          due: ctx.due,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.tasks.update',
    domain: 'google',
    intents: ['edit'],
    description: 'Update a Google Task',
    triggers: ['complete task', 'mark done', 'update task', 'change task'],
    negativeTriggers: ['create task', 'list tasks'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'task is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which task.',
      },
      {
        id: 'update',
        action: 'tool',
        tool: 'updateGoogleTask',
        argsBuilder: (ctx) => ({
          taskId: ctx.taskId,
          title: ctx.title,
          completed: ctx.completed,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.tasks.delete',
    domain: 'google',
    intents: ['delete'],
    description: 'Delete a Google Task',
    triggers: ['delete task', 'remove task', 'remove to-do'],
    negativeTriggers: ['create task', 'list tasks'],
    risk: 'destructive',
    destructive: true,
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'task is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which task.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'delete',
        action: 'tool',
        tool: 'deleteGoogleTask',
        argsBuilder: (ctx) => ({ taskId: ctx.taskId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.contacts.list',
    domain: 'google',
    intents: ['read', 'search'],
    description: 'List or search Google Contacts',
    triggers: ['my contacts', 'google contacts', 'find contact', 'search contacts'],
    negativeTriggers: ['add contact', 'send message'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'listGoogleContacts',
        argsBuilder: (ctx) => ({ query: ctx.query }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'google.contacts.create',
    domain: 'google',
    intents: ['create'],
    description: 'Create a Google Contact',
    triggers: ['add contact', 'new contact', 'save contact', 'create contact'],
    negativeTriggers: ['list contacts', 'find contact'],
    risk: 'write',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'create',
        action: 'tool',
        tool: 'createGoogleContact',
        argsBuilder: (ctx) => ({
          name: ctx.name,
          email: ctx.email,
          phone: ctx.phone,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.contacts.update',
    domain: 'google',
    intents: ['edit'],
    description: 'Update a Google Contact',
    triggers: ['update contact', 'change contact', 'edit contact'],
    negativeTriggers: ['list contacts', 'delete contact'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which contact.',
      },
      {
        id: 'update',
        action: 'tool',
        tool: 'updateGoogleContact',
        argsBuilder: (ctx) => ({
          contactId: ctx.contactId,
          name: ctx.name,
          email: ctx.email,
          phone: ctx.phone,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.contacts.delete',
    domain: 'google',
    intents: ['delete'],
    description: 'Delete a Google Contact',
    triggers: ['delete contact', 'remove contact'],
    negativeTriggers: ['list contacts', 'update contact'],
    risk: 'destructive',
    destructive: true,
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which contact.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'delete',
        action: 'tool',
        tool: 'deleteGoogleContact',
        argsBuilder: (ctx) => ({ contactId: ctx.contactId }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'google.youtube.search',
    domain: 'google',
    intents: ['search'],
    description: 'Search YouTube videos',
    triggers: ['youtube', 'find a video', 'search youtube', 'tutorial on', 'video about'],
    negativeTriggers: ['play a video', 'download a video'],
    risk: 'read',
    steps: [
      {
        id: 'search',
        action: 'tool',
        tool: 'searchYoutube',
        argsBuilder: (ctx) => ({
          query: ctx.query,
          maxResults: ctx.maxResults,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
];

export default googleSkills;
