import type { SkillRoute } from './types.js';

export const mediaSkills: SkillRoute[] = [
  {
    id: 'media.image.generate',
    domain: 'media',
    intents: ['create', 'generate'],
    description: 'Generate an image from a text prompt',
    triggers: ['generate an image', 'create an image', 'make a picture', 'draw', 'illustration', 'logo', 'artwork', 'photo of', 'image of', 'picture of'],
    negativeTriggers: ['edit this image', 'remove from', 'change the', 'update the image', 'what is this image', 'video', 'animate'],
    risk: 'generate',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Prompt is valid for image generation.',
        onFailure: 'Ask for a clear image description.',
      },
      {
        id: 'generate',
        action: 'tool',
        tool: 'qwenImageGenerate',
        argsBuilder: (ctx) => ({
          prompt: ctx.prompt,
          size: ctx.size,
          model: ctx.model,
        }),
        required: true,
        onSuccess: 'Image generated.',
        onFailure: 'Report the generation error.',
      },
      {
        id: 'verify',
        action: 'verify',
        onSuccess: 'Image is valid.',
        onFailure: 'Retry or suggest edits.',
      },
      {
        id: 'respond',
        action: 'respond',
        onSuccess: 'Show the generated image.',
      },
    ],
    successCriteria: [
      { name: 'image_created', description: 'An image file or URL was returned' },
    ],
    outputMode: 'media',
  },
  {
    id: 'media.image.edit',
    domain: 'media',
    intents: ['edit'],
    description: 'Edit an existing image (inpaint, style transfer, modification)',
    triggers: ['edit this image', 'modify this image', 'remove the', 'change the', 'add', 'replace', 'inpaint', 'style transfer', 'make it look like'],
    negativeTriggers: ['generate a new image', 'create an image from scratch', 'what is in this image'],
    risk: 'generate',
    requiredContext: ['activeImage'],
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'No active image in context',
        onSuccess: 'Image reference resolved.',
        onFailure: 'Ask the user to provide an image or refer to one.',
      },
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Edit instruction is valid.',
        onFailure: 'Ask for a clearer edit instruction.',
      },
      {
        id: 'edit',
        action: 'tool',
        tool: 'qwenImageEdit',
        argsBuilder: (ctx) => ({
          prompt: ctx.prompt,
          imageUrl: ctx.activeImage,
        }),
        required: true,
        onSuccess: 'Image edited.',
        onFailure: 'Report the edit error.',
      },
      {
        id: 'verify',
        action: 'verify',
        onSuccess: 'Edited image is valid.',
        onFailure: 'Retry with adjusted parameters.',
      },
      {
        id: 'respond',
        action: 'respond',
        onSuccess: 'Show the edited image.',
      },
    ],
    successCriteria: [
      { name: 'image_edited', description: 'Modified image was produced' },
    ],
    outputMode: 'media',
  },
  {
    id: 'media.video.generate',
    domain: 'media',
    intents: ['create', 'generate'],
    description: 'Generate a video from a text prompt (canonical route)',
    triggers: ['generate a video', 'create a video', 'make a video', 'video of', 'animate', 'short clip', 'cinematic', 'motion', 'video'],
    negativeTriggers: ['edit this video', 'what is this video', 'transcribe the video', 'download this video'],
    risk: 'generate',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Prompt is valid for video generation.',
        onFailure: 'Ask for a clear video description.',
      },
      {
        id: 'generate',
        action: 'tool',
        tool: 'qwenVideoGenerate',
        argsBuilder: (ctx) => ({
          prompt: ctx.prompt,
          size: ctx.size,
          duration: ctx.duration,
        }),
        required: true,
        onSuccess: 'Video generation started.',
        onFailure: 'Report the generation error.',
      },
      {
        id: 'respond',
        action: 'respond',
        onSuccess: 'Inform the user the video is generating.',
      },
    ],
    successCriteria: [
      { name: 'video_started', description: 'Video generation was initiated' },
    ],
    outputMode: 'media',
  },
  {
    id: 'media.video.continue',
    domain: 'media',
    intents: ['edit', 'create'],
    description: 'Continue, extend, or edit an existing video',
    triggers: ['continue this video', 'extend the video', 'make it longer', 'add more', 'edit the video', 'change the video'],
    negativeTriggers: ['generate a new video', 'what is in this video'],
    risk: 'generate',
    requiredContext: ['activeVideo'],
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'No active video in context',
        onSuccess: 'Video reference resolved.',
        onFailure: 'Ask the user to provide a video or refer to one.',
      },
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Continue instruction is valid.',
        onFailure: 'Ask for a clearer instruction.',
      },
      {
        id: 'generate',
        action: 'tool',
        tool: 'qwenVideoGenerate',
        argsBuilder: (ctx) => ({
          prompt: ctx.prompt,
          imageUrl: ctx.activeVideo,
        }),
        required: true,
        onSuccess: 'Video continuation started.',
        onFailure: 'Report the error.',
      },
      {
        id: 'respond',
        action: 'respond',
        onSuccess: 'Inform the user.',
      },
    ],
    successCriteria: [
      { name: 'video_continued', description: 'Video continuation was initiated' },
    ],
    outputMode: 'media',
  },
  {
    id: 'media.audio.tts',
    domain: 'media',
    intents: ['create', 'generate', 'execute'],
    description: 'Text-to-speech: narrate text, generate voice audio',
    triggers: ['read this aloud', 'narrate', 'text to speech', 'tts', 'say this', 'speak', 'voice this', 'generate speech', 'read it out'],
    negativeTriggers: ['generate an image', 'create a video', 'send a message', 'what does this say'],
    risk: 'generate',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Text is valid for TTS.',
        onFailure: 'Ask for the text to narrate.',
      },
      {
        id: 'generate',
        action: 'tool',
        tool: 'qwenTts',
        argsBuilder: (ctx) => ({
          text: ctx.text,
          voice: ctx.voice,
          speed: ctx.speed,
        }),
        required: true,
        onSuccess: 'Audio generated.',
        onFailure: 'Report the TTS error.',
      },
      {
        id: 'respond',
        action: 'respond',
        onSuccess: 'Play or share the generated audio.',
      },
    ],
    successCriteria: [
      { name: 'audio_created', description: 'An audio file or URL was returned' },
    ],
    outputMode: 'media',
  },
  {
    id: 'media.chat',
    domain: 'media',
    intents: ['conversation', 'question'],
    description: 'General chat with QwenCloud LLM (non-visual)',
    triggers: [],
    risk: 'read',
    steps: [
      {
        id: 'chat',
        action: 'tool',
        tool: 'qwenChat',
        argsBuilder: (ctx) => ({
          messages: ctx.messages,
        }),
        required: true,
        onSuccess: 'Return the response.',
        onFailure: 'Fall back to direct Gemini conversation.',
      },
      {
        id: 'respond',
        action: 'respond',
        onSuccess: 'Return Qwen response.',
      },
    ],
    outputMode: 'text',
  },
];

export default mediaSkills;
