import type { SkillRoute } from './types.js';

export const whatsappSkills: SkillRoute[] = [
  {
    id: 'whatsapp.resolve_contact',
    domain: 'whatsapp',
    intents: ['read', 'search'],
    description: 'Resolve a name to a verified WhatsApp contact — never invent JIDs or numbers',
    triggers: ['who is', 'find', 'resolve', 'look up the contact', 'number for'],
    negativeTriggers: ['send', 'message', 'call', 'on whatsapp', 'who is on'],
    risk: 'read',
    steps: [
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Contact name is specified.',
        onFailure: 'Ask which contact to resolve.',
      },
      {
        id: 'resolve',
        action: 'tool',
        tool: 'resolve_whatsapp_contact',
        argsBuilder: (ctx) => ({ name: ctx.name || ctx.contact }),
        required: true,
        onSuccess: 'Contact resolved from real WhatsApp data.',
        onFailure: 'Report the error — do not fabricate contact details.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.list_contacts',
    domain: 'whatsapp',
    intents: ['read', 'search'],
    description: 'List or search WhatsApp contacts',
    triggers: ['whatsapp contacts', 'wa contacts', 'who is on whatsapp', 'find contact on whatsapp'],
    negativeTriggers: ['send a message', 'call'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'get_whatsapp_contacts',
        argsBuilder: (ctx) => ({ query: ctx.query }),
        required: true,
        onSuccess: 'Return the contacts.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.list_chats',
    domain: 'whatsapp',
    intents: ['read'],
    description: 'List WhatsApp chat conversations',
    triggers: ['whatsapp chats', 'wa chats', 'my conversations', 'chat list', 'message list'],
    negativeTriggers: ['send a message', 'read message history'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'read_whatsapp_chats',
        required: true,
        onSuccess: 'Return the chats.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.read_history',
    domain: 'whatsapp',
    intents: ['read'],
    description: 'Read message history for a specific chat',
    triggers: ['read my chat with', 'conversation with', 'message history', 'what did', 'chat history', 'show messages from'],
    negativeTriggers: ['send a message', 'list chats'],
    risk: 'read',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Contact resolved.',
        onFailure: 'Ask which chat to read.',
      },
      {
        id: 'read',
        action: 'tool',
        tool: 'get_whatsapp_message_history',
        argsBuilder: (ctx) => ({
          contactJid: ctx.contactJid,
          limit: ctx.limit,
        }),
        required: true,
        onSuccess: 'Return the messages.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.list_groups',
    domain: 'whatsapp',
    intents: ['read'],
    description: 'List WhatsApp groups',
    triggers: ['whatsapp groups', 'wa groups', 'group list', 'my groups'],
    negativeTriggers: ['send to group', 'message the group'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'get_whatsapp_groups',
        required: true,
        onSuccess: 'Return the groups.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.list_calls',
    domain: 'whatsapp',
    intents: ['read'],
    description: 'List WhatsApp call history',
    triggers: ['whatsapp calls', 'wa calls', 'call history', 'who called me'],
    negativeTriggers: ['make a call', 'send a message'],
    risk: 'read',
    steps: [
      {
        id: 'list',
        action: 'tool',
        tool: 'get_whatsapp_calls',
        required: true,
        onSuccess: 'Return the calls.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.send_message',
    domain: 'whatsapp',
    intents: ['send', 'create'],
    description: 'Send a WhatsApp text message (with human approval gate)',
    triggers: ['send a whatsapp', 'text on whatsapp', 'message on whatsapp', 'send a wa', 'send to', 'whatsapp message', 'wa message'],
    negativeTriggers: ['read my chats', 'list contacts', 'show messages', 'send an email'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Contact resolved.',
        onFailure: 'Ask who to send to.',
      },
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Message content is valid.',
        onFailure: 'Ask what message to send.',
      },
      {
        id: 'request_approval',
        action: 'tool',
        tool: 'request_whatsapp_send',
        argsBuilder: (ctx) => ({
          recipient: ctx.recipient,
          text: ctx.text ?? ctx.message,
        }),
        required: true,
        onSuccess: 'User approved.',
        onFailure: 'User rejected or timed out.',
      },
      {
        id: 'send',
        action: 'tool',
        tool: 'send_whatsapp_text',
        argsBuilder: (ctx) => ({
          recipient: ctx.recipient,
          text: ctx.text ?? ctx.message,
        }),
        required: true,
        onSuccess: 'Message sent.',
        onFailure: 'Report the send error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    successCriteria: [
      { name: 'message_sent', description: 'WhatsApp message was delivered' },
    ],
    outputMode: 'action',
  },
  {
    id: 'whatsapp.send_document',
    domain: 'whatsapp',
    intents: ['send'],
    description: 'Send a document/file via WhatsApp',
    triggers: ['send this file', 'send the document', 'whatsapp file', 'send document'],
    negativeTriggers: ['send a text message', 'send an image'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Contact resolved.',
        onFailure: 'Ask who to send to.',
      },
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'File is valid.',
        onFailure: 'Ask for the file to send.',
      },
      {
        id: 'request_approval',
        action: 'tool',
        tool: 'request_whatsapp_send',
        required: true,
        onSuccess: 'User approved.',
        onFailure: 'User rejected.',
      },
      {
        id: 'send',
        action: 'tool',
        tool: 'send_whatsapp_document',
        argsBuilder: (ctx) => ({
          recipient: ctx.recipient,
          filePath: ctx.filePath,
          fileName: ctx.fileName,
        }),
        required: true,
        onSuccess: 'Document sent.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'whatsapp.send_group_message',
    domain: 'whatsapp',
    intents: ['send'],
    description: 'Send a message to a WhatsApp group',
    triggers: ['send to the group', 'message the group', 'group message', 'send to family group', 'send to team group'],
    negativeTriggers: ['send a private message', 'list groups'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'group is ambiguous',
        onSuccess: 'Group resolved.',
        onFailure: 'Ask which group to send to.',
      },
      {
        id: 'validate',
        action: 'validate',
        required: true,
        onSuccess: 'Message is valid.',
        onFailure: 'Ask what to send.',
      },
      {
        id: 'request_approval',
        action: 'tool',
        tool: 'request_whatsapp_send',
        required: true,
        onSuccess: 'Approved.',
        onFailure: 'Rejected.',
      },
      {
        id: 'send',
        action: 'tool',
        tool: 'send_whatsapp_group_message',
        argsBuilder: (ctx) => ({
          groupJid: ctx.groupJid,
          text: ctx.text,
        }),
        required: true,
        onSuccess: 'Group message sent.',
        onFailure: 'Report the error.',
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'whatsapp.send_contact_card',
    domain: 'whatsapp',
    intents: ['send'],
    description: 'Send a contact card via WhatsApp',
    triggers: ['send contact card', 'share contact', 'send a contact'],
    negativeTriggers: ['send a text', 'send a document'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask who to send.',
      },
      {
        id: 'validate',
        action: 'validate',
        required: true,
      },
      {
        id: 'request_approval',
        action: 'tool',
        tool: 'request_whatsapp_send',
        required: true,
      },
      {
        id: 'send',
        action: 'tool',
        tool: 'send_whatsapp_contact_card',
        argsBuilder: (ctx) => ({
          recipient: ctx.recipient,
          contactJid: ctx.contactJid,
          contactName: ctx.contactName,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'whatsapp.block',
    domain: 'whatsapp',
    intents: ['control'],
    description: 'Block a WhatsApp contact',
    triggers: ['block on whatsapp', 'block this number', 'block contact'],
    negativeTriggers: ['unblock', 'send a message'],
    risk: 'destructive',
    destructive: true,
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask who to block.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'block',
        action: 'tool',
        tool: 'block_whatsapp_contact',
        argsBuilder: (ctx) => ({ contactJid: ctx.contactJid }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'whatsapp.unblock',
    domain: 'whatsapp',
    intents: ['control'],
    description: 'Unblock a WhatsApp contact',
    triggers: ['unblock on whatsapp', 'unblock contact', 'remove block'],
    negativeTriggers: ['block'],
    risk: 'write',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask who to unblock.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'unblock',
        action: 'tool',
        tool: 'unblock_whatsapp_contact',
        argsBuilder: (ctx) => ({ contactJid: ctx.contactJid }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
  {
    id: 'whatsapp.read_attachment',
    domain: 'whatsapp',
    intents: ['read'],
    description: 'Read or download a WhatsApp attachment',
    triggers: ['open attachment', 'download attachment', 'read the image', 'open the file'],
    negativeTriggers: ['send an attachment'],
    risk: 'read',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'attachment is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which attachment.',
      },
      {
        id: 'read',
        action: 'tool',
        tool: 'read_whatsapp_attachment',
        argsBuilder: (ctx) => ({ mediaKey: ctx.mediaKey, mimeType: ctx.mimeType }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.transcribe_audio',
    domain: 'whatsapp',
    intents: ['read', 'execute'],
    description: 'Transcribe a WhatsApp audio/voice message',
    triggers: ['transcribe', 'what did they say', 'voice message', 'audio message', 'what was said'],
    negativeTriggers: ['send audio', 'play audio'],
    risk: 'read',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'audio message is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask which voice message.',
      },
      {
        id: 'transcribe',
        action: 'tool',
        tool: 'transcribe_whatsapp_audio',
        argsBuilder: (ctx) => ({ mediaKey: ctx.mediaKey }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.sync',
    domain: 'whatsapp',
    intents: ['execute'],
    description: 'Sync WhatsApp message history from server',
    triggers: ['sync whatsapp', 'refresh chats', 'update messages'],
    negativeTriggers: ['read chats', 'send a message'],
    risk: 'read',
    steps: [
      {
        id: 'sync',
        action: 'tool',
        tool: 'sync_whatsapp_history',
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'text',
  },
  {
    id: 'whatsapp.call',
    domain: 'whatsapp',
    intents: ['execute', 'control'],
    description: 'Initiate a WhatsApp voice or video call',
    triggers: ['call on whatsapp', 'whatsapp call', 'voice call', 'video call on whatsapp'],
    negativeTriggers: ['send a message', 'list calls'],
    risk: 'execute',
    steps: [
      {
        id: 'resolve',
        action: 'resolve',
        when: 'contact is ambiguous',
        onSuccess: 'Resolved.',
        onFailure: 'Ask who to call.',
      },
      {
        id: 'confirm',
        action: 'confirm',
        required: true,
      },
      {
        id: 'call',
        action: 'tool',
        tool: 'whatsapp_call',
        argsBuilder: (ctx) => ({
          contactJid: ctx.contactJid,
          callType: ctx.callType,
        }),
        required: true,
      },
      { id: 'respond', action: 'respond' },
    ],
    outputMode: 'action',
  },
];

export default whatsappSkills;
